### ISSUE TITLE
wrong argument type Integer (expected Integer)

### ISSUE THREAD

**Issue by alxx** [sirupsen/sysvmq#15]
Trying to initialize a queue on a Raspberry Pi, I get the weird error above.

```
pi@rasp:~ $ irb
irb(main):001:0> require 'sysvmq'
=> true
irb(main):002:0> vmq = SysVMQ.new(0xDEADC0DE, 1024, SysVMQ::IPC_CREAT | 0666)
(irb):2:in `initialize': wrong argument type Integer (expected Integer) (TypeError)
        from (irb):2:in `new'            
        from (irb):2:in `<main>'         
        from /snap/ruby/264/lib/ruby/gems/3.1.0/gems/irb-1.4.1/exe/irb:11:in `<top (required)>'
        from /snap/ruby/264/bin/irb:25:in `load'
        from /snap/ruby/264/bin/irb:25:in `<main>'
irb(main):003:0> 
pi@rasp:~ $ uname -a                    
Linux rasp 5.10.92-v7+ #1514 SMP Mon Jan 17 17:36:39 GMT 2022 armv7l GNU/Linux
pi@rasp:~ $ ruby -v                     
ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [armv7l-linux-eabihf]

```
Any ideas?

**Comment by sirupsen** [comment]
`wrong argument type Integer (expected Integer)` is a very weird exception—no, I'm not sure, and I can't reproduce it on a Linux VM. Please let me know if you figure it out.

**Comment by alxx** [comment]
I switched over to posix-mqueue and that worked fine, although it shows some really high CPU loads when I stream data at higher speeds. Fortunately in my scenario those are just peaks.

As for the exception mentioned here, I have no idea what to do about it -- the stack trace is unhelpful as you see, and my FFI skills are very limited. I can only speculate that Raspbian isn't SysV compatible and the exception is a misinterpretation of that fact...

It might also be related to Ruby 3.1.1, what version did you use in your VM?

**Comment by sirupsen** [comment]
> Raspbian isn't SysV compatible
 
It's possible, but I'd find it strange to disable on the Linux build—e.g. Postgres uses SysV for some IPC. But I'm running the exact same Ruby version and patch-level as you on a 5.13 kernel, no problems.

> although it shows some really high CPU loads when I stream data at higher speeds. Fortunately in my scenario those are just peaks.

`posix-mqueue` isn't production-hardened (at least not by me or former employers) in the same way as `sysvmq`, so there might be room for optimization in the code. The nice thing about `posix-mqueue` is that it exposes file descriptors, which is far superior for dealing with a VM runtime. There may be newer APIs for dealing with this and the GIL in newer versions. Probably a really fun thing to profile for your workload(s) :)

**Comment by alxx** [comment]
Thanks for writing back. I'd love to be able to get back to using `sysvmq`, but I wouldn't even know where to look in order to debug this. I can't find anything online related to System V queues on Raspbian. You're right about mountable file descriptors being an advantage, but right now I'll take performance over convenience :)

**Comment by sirupsen** [comment]
Pick your poison 💀 —figure out how to speed up `posix-mq` or debug `sysvmq` 😉 

Try to see if the [`ipcs(1)`/`lsipc(1)` tooling works](https://man7.org/linux/man-pages/man1/ipcs.1.html). That'll tell you for sure if SysV IPC is straight-up disabled.

**Comment by alxx** [comment]
I found this interesting comment:

https://github.com/sirupsen/sysvmq/blob/0b042308184513b759e4820a162937c13663f970/ext/sysvmq.c#L359

Is there any easy way for me to check what `key_t` might be defined as on Raspbian?

**Comment by sirupsen** [comment]
Locate the sys/types.h header on your system

Simon
https://sirupsen.com/

**Comment by alxx** [comment]
Might it be this thing? It's an odd path but I can't find any other sys/types.h anywhere in my system.

https://github.com/raspberrypi/tools/blob/13474ee775d0c5ec8a7da4fb0a9fa84187abfc87/arm-bcm2708/arm-bcm2708-linux-gnueabi/arm-bcm2708-linux-gnueabi/sysroot/usr/include/sys/types.h#L125

**Comment by alxx** [comment]
Sorry, you credit me with more C than I have :) I would appreciate some more detailed instructions on how to do that, if you have the time.

**Comment by sirupsen** [comment]
I'm confident you can figure it out and would learn a lot doing it! I don't have the cycles to produce more instructions than this though:

`bundle exec rake compile` produces a `.so` file. You can directly `require` that in `irb`, which is the library. That should give you a feedback loop.

**Comment by alxx** [comment]
It won't compile at all... 

```
$ bundle exec rake compile
/snap/ruby/264/lib/ruby/3.1.0/bundler/vendor/fileutils/lib/fileutils.rb:105: warning: already initialized constant Bundler::FileUtils::VERSION
/home/pi/.gem/gems/bundler-2.3.8/lib/bundler/vendor/fileutils/lib/fileutils.rb:105: warning: previous definition of VERSION was here
/snap/ruby/264/lib/ruby/3.1.0/bundler/vendor/fileutils/lib/fileutils.rb:1284: warning: already initialized constant Bundler::FileUtils::Entry_::S_IF_DOOR
/home/pi/.gem/gems/bundler-2.3.8/lib/bundler/vendor/fileutils/lib/fileutils.rb:1284: warning: previous definition of S_IF_DOOR was here
/snap/ruby/264/lib/ruby/3.1.0/bundler/vendor/fileutils/lib/fileutils.rb:1568: warning: already initialized constant Bundler::FileUtils::Entry_::DIRECTORY_TERM
/home/pi/.gem/gems/bundler-2.3.8/lib/bundler/vendor/fileutils/lib/fileutils.rb:1568: warning: previous definition of DIRECTORY_TERM was here
/snap/ruby/264/lib/ruby/3.1.0/bundler/vendor/fileutils/lib/fileutils.rb:1626: warning: already initialized constant Bundler::FileUtils::OPT_TABLE
/home/pi/.gem/gems/bundler-2.3.8/lib/bundler/vendor/fileutils/lib/fileutils.rb:1626: warning: previous definition of OPT_TABLE was here
/snap/ruby/264/lib/ruby/3.1.0/bundler/vendor/fileutils/lib/fileutils.rb:1685: warning: already initialized constant Bundler::FileUtils::LOW_METHODS
/home/pi/.gem/gems/bundler-2.3.8/lib/bundler/vendor/fileutils/lib/fileutils.rb:1685: warning: previous definition of LOW_METHODS was here
/snap/ruby/264/lib/ruby/3.1.0/bundler/vendor/fileutils/lib/fileutils.rb:1692: warning: already initialized constant Bundler::FileUtils::METHODS
/home/pi/.gem/gems/bundler-2.3.8/lib/bundler/vendor/fileutils/lib/fileutils.rb:1692: warning: previous definition of METHODS was here
rake aborted!
ArgumentError: Trying to register Bundler::GemfileError for status code 4 but Bundler::GemfileError is already registered
/tmp/sysvmq/Rakefile:1:in `require'
/tmp/sysvmq/Rakefile:1:in `<top (required)>'
(See full trace by running task with --trace)
```

I've even tried upgrading `rake-compile` to the latest version in your gemspec, but it didn't help.

```
$ bundle list
Gems included by the bundle:
  * rake (13.0.6)
  * rake-compiler (1.1.9)
  * sysvmq (0.2.2)
```

I've compiled it on my Mac though without problems, but there were no `.so` files anywhere:

```
➜  sysvmq git:(master) ✗ find . -type f -name "*.so"
➜  sysvmq git:(master) ✗ # nothing here :)
```

**Comment by sirupsen** [comment]
```bash
sysv-mq $ bx rake compile
mkdir -p tmp/arm64-darwin21/sysvmq/3.1.0
cd tmp/arm64-darwin21/sysvmq/3.1.0
/Users/simon/.rubies/ruby-3.1.0/bin/ruby -I. ../../../../ext/extconf.rb
checking for sys/ipc.h... yes
checking for sys/msg.h... yes
checking for sys/types.h... yes
checking for rb_thread_blocking_region()... no
checking for rb_thread_call_without_gvl()... yes
creating Makefile
cd -
cd tmp/arm64-darwin21/sysvmq/3.1.0
/usr/bin/make
compiling ../../../../ext/sysvmq.c
linking shared-object sysvmq.bundle
cd -
mkdir -p tmp/arm64-darwin21/stage/lib
install -c tmp/arm64-darwin21/sysvmq/3.1.0/sysvmq.bundle lib/sysvmq.bundle
cp tmp/arm64-darwin21/sysvmq/3.1.0/sysvmq.bundle tmp/arm64-darwin21/stage/lib/sysvmq.bundle
sysv-mq $ irb
irb(main):001:0> require_relative './lib/sysvmq.bundle'
=> true
irb(main):002:0> SysVMQ
=> SysVMQ
```

Sorry, I don't have the cycles to debug it with you on Raspberry Pi. Google hard enough and you'll be able to work through it
